name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t foodzy:latest .

    - name: Start website container
      run: docker run -d --name new-apples -p 80:80 -p 443:443 foodzy:latest 

    - name: Start ZAP
      run: docker run -d --name security-site -p 8080:8080 -m 4g  ghcr.io/zaproxy/zaproxy:stable zap.sh -daemon -host 0.0.0.0 -port 8080

    - name: Wait for ZAP to start
      run: sleep 60

    - name: Run ZAP quick scan
      run: docker exec security-site zap-baseline.py -t https://apples.foodzy.pp.ua -J /zap/zap_out.json
   
    - name: Copy ZAP report
      run: docker cp security-site:/zap/zap_out.json .
    
    - name: Stop ZAP
      run: docker stop security-site

    - name: Stop website container
      run: docker stop new-apples
