name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/foodzy:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/foodzy:latest

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/foodzy:latest
          docker stop new-apples || true
          docker rm new-apples || true
          docker run -d --name new-apples -p 80:80 -p 443:443 ${{ secrets.DOCKER_USERNAME }}/foodzy:latest
        EOF



   
