name: GitHub Actions 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/foodzy:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/foodzy:latest

    - name: Deploy to server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > privkey.pem
        echo "${{ secrets.SSL_PRIVKEY }}" > ssl_privkey.pem 
        echo "${{ secrets.SSL_FULLCHAIN }}" > ssl_fullchain.pem
        chmod 600 privkey.pem
        ssh -tt -o StrictHostKeyChecking=no -i privkey.pem adminserver@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/foodzy:latest
          docker stop new-apples || true
          docker rm new-apples || true
          docker run -d --name new-apples -p 80:80 -p 443:443 -v /diplom/ssl:/etc/ssl -v /diplom/ssl/fullchain.pem:/etc/ssl/certs/fullchain.pem ${{ secrets.DOCKER_USERNAME }}/foodzy:latest
        EOF



   
