name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Decode SSL files from secrets
      run: |
        echo "${{ secrets.FULLCHAIN_PEM_B64 }}" | base64 -d > fullchain.pem
        echo "${{ secrets.PRIVKEY_PEM_B64 }}" | base64 -d > privkey.pem

    - name: Validate PEM files
      run: |
        openssl x509 -in fullchain.pem -text -noout || (echo "❌ fullchain.pem пошкоджений" && exit 1)
        openssl rsa -in privkey.pem -check || (echo "❌ privkey.pem пошкоджений" && exit 1)

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodzy:latest

    - name: Clean up PEM files
      run: rm fullchain.pem privkey.pem

    - name: Start ssh-agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP_ADD }}
      run: |
        ssh -tt -o StrictHostKeyChecking=no azureuser@${{ secrets.SERVER_IP_ADD }} "
          docker pull $DOCKER_USERNAME/foodzy:latest &&
          docker stop new-apples || true &&
          docker rm new-apples || true &&
          docker run -d --name new-apples -p 80:80 -p 443:443 $DOCKER_USERNAME/foodzy:latest
        "

    - name: Start ZAP Baseline Scan
      run: docker run --rm -u 0 -v ~/zap_output:/zap/wrk zaproxy/zap-stable zap-baseline.py -t https://apples.foodzy.pp.ua -I -J --auto
 
