name: Scan for Project

on: 
  push:
    branches:
      - main

jobs:
  scan-project:
    runs-on: ubuntu 22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Start website container
      run: docker run -d --name new-apples -p 80:80 -p 443:443 foodzy:latest 

    - name: Start ZAP
      run: docker run -d --name security-site -p 8080:8080 owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080

    - name: Wait for ZAP to start
      run: sleep 30

    - name: Run ZAP scan
      run: docker exec zap zap-cli quick-scan https://apples.foodzy.pp.ua

    - name: Stop ZAP
      run: docker stop security-site

  
